# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a9abb80832d86717d1787ab3e5ab2d319d405c74b64dbc0dadf230727e3cbd335a3dc4c646733544d34821a2f21bb2cd1fdd235c4156115237ada769c5220fa

test:
  secret_key_base: dde754db95343dd8a8d58b70016a6ebdf014d3e129d1e7b42946a55f5973ae2f111b312c69d6b593748b319c9bc6d5c6fbce37b660c36c3aec413562982d6e27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
